- name: SNAX Issue One
  img: assets/images/issueone_square.JPG
  price: $20
  url: /issueone

- name: SNAX Issue One PDF
  img: assets/images/i1pdf_square.png
  price: $10
  url: /pdf

- name: Logo hat
  img: assets/images/hat.png
  price: $20
  url: /hat

- name: Embroidered sweatshirt
  img: assets/images/sweatshirt.png
  price: $28
  url: /sweatshirt

- name: Embroidered hoodie
  img: assets/images/hoodie.png
  price: $30
  url: /hoodie
